spring:
  application:
    name: ms-clientes

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://ms-eureka-user:rre-easme-usuk@localhost:8761/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  file:
    name: ./log/log-file.log
